package lib.minecraft.text.font;

import org.jetbrains.annotations.NotNull;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;

/**
 * Loads the committed synthetic colour-font fixtures ({@code src/test/resources/colorfont}) that
 * back the colour-glyph test suite. Every fixture is generated by the {@code gen_fixtures.py}
 * pipeline from synthetic cells - no real pack assets.
 */
final class ColorFontFixtures {

    static final @NotNull FontId DEMO = FontId.parse("synth:demo");
    static final @NotNull FontId ALT = FontId.parse("synth:alt");

    // demo raster glyphs
    static final int CP_FLAT = 0xE001;       // gid 1, strike ppem 8, 8x8 red/blue (fully opaque)
    static final int CP_AA = 0xE002;         // gid 2, strike ppem 8, 8x8 anti-aliased multi-colour
    static final int CP_FLAT_DUP = 0xE003;   // gid 1 (dedup of CP_FLAT)
    static final int CP_MID = 0xE004;        // gid 3, strike ppem 8, 16x16
    static final int CP_DOWNSCALED = 0xE005; // gid 4, strike ppem 16, 16x16
    static final int CP_TALL = 0xE006;       // gid 5, strike ppem 8, 256x256
    // demo space glyphs
    static final int CP_NEG_SPACE = 0xE010;  // advance -1024 units = -16 output px
    static final int CP_FRAC_SPACE = 0xE011; // advance 96 units = 1.5 output px

    private ColorFontFixtures() {}

    static byte[] bytes(@NotNull String name) {
        try (InputStream in = ColorFontFixtures.class.getClassLoader().getResourceAsStream("colorfont/" + name)) {
            if (in == null) throw new IllegalStateException("Missing colour-font fixture: colorfont/" + name);
            return in.readAllBytes();
        } catch (IOException ex) {
            throw new UncheckedIOException(ex);
        }
    }

    static @NotNull Reader sidecarReader() {
        InputStream in = ColorFontFixtures.class.getClassLoader().getResourceAsStream("colorfont/colour-glyphs.json");
        if (in == null) throw new IllegalStateException("Missing colour sidecar fixture");
        return new InputStreamReader(in, StandardCharsets.UTF_8);
    }

    static @NotNull ColorGlyphSidecar sidecar() {
        try (Reader reader = sidecarReader()) {
            return ColorGlyphSidecar.parse(reader);
        } catch (IOException ex) {
            throw new UncheckedIOException(ex);
        }
    }

    static @NotNull SbixReader edgeReader() {
        return new SbixReader(bytes("SynthColour-edge.ttf"));
    }

    // Colour-font-backed helpers (demoFont/altFont) are added alongside the pack colour-font layer.

}
